<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="index.php" method="post">
    <input type="text" name="nombre" placeholder="Nombre">
    <input type="password" name="password" placeholder="Contraseña">
    <input type="submit" name="crear_cuenta" value="Crear Cuenta">
</body>
</html>