<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- Login: el submit se llama login, que es lo que comprueba mainController.php -->
    <form action="index.php" method="post">
    <input type="text" name="nombre" placeholder="Nombre">
    <input type="password" name="password" placeholder="Contraseña">
    <input type="submit" value="Login" name="login">
</body>
</html>