<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
        <h1>Bienvenido al Blog</h1>
            <a href="index.php?opc=inicio">Inicio</a>
            <a href="index.php?opc=login">Login</a>
            <a href="index.php?opc=crear_cuenta">Crear Cuenta</a>
            <a href="index.php?opc=articulos">Articulos publicados</a>
            <a href="index.php?opc=redactar">Redactar Articulo</a>
            <a href="index.php?opc=logout">Cerrar sesion</a>
</body>
</html>