<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Nuevo post</h2>
    <form action="index.php?opc=redactar" method="post">
    <input type="text" name="titulo" placeholder="Titulo">
    <br>
    <textarea name="contenido" placeholder="Contenido"></textarea>
    <br>
    <input type="submit" name="publicar" value="Publicar">
    </form>
</body>
</html>